DROP TABLE CLI IF EXISTS;

CREATE TABLE CLI  (
    ROW_ID_SIEBEL 			VARCHAR(15) NOT NULL,
    CODE_CLIENT 			VARCHAR(30) UNIQUE NOT NULL,
    NOM_CLIENT  			VARCHAR(100) NOT NULL,    
	STATUT_CRM				VARCHAR(15) NOT NULL,
	ROLE_CLIENT				VARCHAR(15) NOT NULL,
	NIV_HIERARCHIE_CLIENT	VARCHAR(20) NOT NULL,
	NOM_GROUPE				VARCHAR(100),
	ID_GROUPE				VARCHAR(15),
	NOM_CLIENT_PARENT		VARCHAR(100),
	CODE_CLIENT_PARENT		VARCHAR(30),
	CLIENT_FACTURE			VARCHAR(1) NOT NULL,
	A_CONTROLLER			VARCHAR(1),
	GROUPE_FACTURATION		VARCHAR(30),
	NO_PARENT_ERROR			VARCHAR(1),
	PRIMARY KEY (ROW_ID_SIEBEL)    
);

